[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

gas_reports = [
    "AccessController",
    "ImplementationManager",
    "ConfigManager",
    "TokenWhitelist",
    "NFTCollectionWhitelist",
    "ClooverRaffleFactory",
    "ClooverRaffle"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
sepolia = {key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config