[profile.default]
names = true
sizes = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./config/"}]

gas_reports = [
    "AccessController",
    "ImplementationManager",
    "ConfigManager",
    "TokenWhitelist",
    "NFTCollectionWhitelist",
    "ClooverRaffleFactory",
    "ClooverRaffle"
]

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = {key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config