[profile.default]
names = true
sizes = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./config/"}]

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"

[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config