[profile.default]
names = true
sizes = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./config/"}]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_KEY}"

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}" }
polygon = {key = "${POLYGONSCAN_API_KEY}", chain = 137, url = "https://api.polygonscan.com/api/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

