/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ImplementationInterfaceNamesInterface extends utils.Interface {
  functions: {
    "AccessController()": FunctionFragment;
    "RaffleContract()": FunctionFragment;
    "RandomProvider()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "AccessController"
      | "RaffleContract"
      | "RandomProvider"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "AccessController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RaffleContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RandomProvider",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AccessController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RaffleContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RandomProvider",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ImplementationInterfaceNames extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ImplementationInterfaceNamesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    AccessController(overrides?: CallOverrides): Promise<[string]>;

    RaffleContract(overrides?: CallOverrides): Promise<[string]>;

    RandomProvider(overrides?: CallOverrides): Promise<[string]>;
  };

  AccessController(overrides?: CallOverrides): Promise<string>;

  RaffleContract(overrides?: CallOverrides): Promise<string>;

  RandomProvider(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    AccessController(overrides?: CallOverrides): Promise<string>;

    RaffleContract(overrides?: CallOverrides): Promise<string>;

    RandomProvider(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    AccessController(overrides?: CallOverrides): Promise<BigNumber>;

    RaffleContract(overrides?: CallOverrides): Promise<BigNumber>;

    RandomProvider(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    AccessController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RaffleContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RandomProvider(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
