/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IConfigManagerInterface extends utils.Interface {
  functions: {
    "maxTicketSalesDuration()": FunctionFragment;
    "maxTicketSupplyAllowed()": FunctionFragment;
    "minTicketSalesDuration()": FunctionFragment;
    "procolFeesPercentage()": FunctionFragment;
    "ticketSalesDurationLimits()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "maxTicketSalesDuration"
      | "maxTicketSupplyAllowed"
      | "minTicketSalesDuration"
      | "procolFeesPercentage"
      | "ticketSalesDurationLimits"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "maxTicketSalesDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTicketSupplyAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTicketSalesDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "procolFeesPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ticketSalesDurationLimits",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "maxTicketSalesDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTicketSupplyAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTicketSalesDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "procolFeesPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketSalesDurationLimits",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IConfigManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IConfigManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    maxTicketSalesDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxTicketSupplyAllowed(overrides?: CallOverrides): Promise<[BigNumber]>;

    minTicketSalesDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    procolFeesPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    ticketSalesDurationLimits(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        minDuration: BigNumber;
        maxDuration: BigNumber;
      }
    >;
  };

  maxTicketSalesDuration(overrides?: CallOverrides): Promise<BigNumber>;

  maxTicketSupplyAllowed(overrides?: CallOverrides): Promise<BigNumber>;

  minTicketSalesDuration(overrides?: CallOverrides): Promise<BigNumber>;

  procolFeesPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  ticketSalesDurationLimits(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { minDuration: BigNumber; maxDuration: BigNumber }
  >;

  callStatic: {
    maxTicketSalesDuration(overrides?: CallOverrides): Promise<BigNumber>;

    maxTicketSupplyAllowed(overrides?: CallOverrides): Promise<BigNumber>;

    minTicketSalesDuration(overrides?: CallOverrides): Promise<BigNumber>;

    procolFeesPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    ticketSalesDurationLimits(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        minDuration: BigNumber;
        maxDuration: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    maxTicketSalesDuration(overrides?: CallOverrides): Promise<BigNumber>;

    maxTicketSupplyAllowed(overrides?: CallOverrides): Promise<BigNumber>;

    minTicketSalesDuration(overrides?: CallOverrides): Promise<BigNumber>;

    procolFeesPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    ticketSalesDurationLimits(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    maxTicketSalesDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxTicketSupplyAllowed(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minTicketSalesDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    procolFeesPercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ticketSalesDurationLimits(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
