/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccessController } from "./IAccessController";
export type { IImplementationManager } from "./IImplementationManager";
export type { IRaffle } from "./IRaffle";
export type { IRaffleFactory } from "./IRaffleFactory";
export type { IRandomProvider } from "./IRandomProvider";
