/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccessController } from "./IAccessController";
export type { IConfigManager } from "./IConfigManager";
export type { IImplementationManager } from "./IImplementationManager";
export type { INFTCollectionWhitelist } from "./INFTCollectionWhitelist";
export type { IClooverRaffle } from "./IClooverRaffle";
export type { IClooverRaffleFactory } from "./IClooverRaffleFactory";
export type { IRandomProvider } from "./IRandomProvider";
export type { ITokenWhitelist } from "./ITokenWhitelist";
