/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IRaffleFactory {
  export type ParamsStruct = {
    purchaseCurrency: PromiseOrValue<string>;
    nftContract: PromiseOrValue<string>;
    nftId: PromiseOrValue<BigNumberish>;
    maxTicketSupply: PromiseOrValue<BigNumberish>;
    ticketPrice: PromiseOrValue<BigNumberish>;
    ticketSaleDuration: PromiseOrValue<BigNumberish>;
  };

  export type ParamsStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    purchaseCurrency: string;
    nftContract: string;
    nftId: BigNumber;
    maxTicketSupply: BigNumber;
    ticketPrice: BigNumber;
    ticketSaleDuration: BigNumber;
  };
}

export interface IRaffleFactoryInterface extends utils.Interface {
  functions: {
    "batchRaffledraw(address[])": FunctionFragment;
    "createNewRaffle((address,address,uint256,uint256,uint256,uint64))": FunctionFragment;
    "isRegisteredRaffle(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchRaffledraw"
      | "createNewRaffle"
      | "isRegisteredRaffle"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchRaffledraw",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewRaffle",
    values: [IRaffleFactory.ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredRaffle",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchRaffledraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredRaffle",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRaffleFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRaffleFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchRaffledraw(
      raffleContracts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createNewRaffle(
      params: IRaffleFactory.ParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isRegisteredRaffle(
      raffleAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  batchRaffledraw(
    raffleContracts: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createNewRaffle(
    params: IRaffleFactory.ParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isRegisteredRaffle(
    raffleAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    batchRaffledraw(
      raffleContracts: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    createNewRaffle(
      params: IRaffleFactory.ParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    isRegisteredRaffle(
      raffleAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    batchRaffledraw(
      raffleContracts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createNewRaffle(
      params: IRaffleFactory.ParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isRegisteredRaffle(
      raffleAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchRaffledraw(
      raffleContracts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createNewRaffle(
      params: IRaffleFactory.ParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isRegisteredRaffle(
      raffleAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
