/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { mockERC20WithPermit } from "./mockERC20WithPermit";
export type { MockERC721 } from "./MockERC721";
export type { MockRandomProvider } from "./MockRandomProvider";
