/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConfigManager,
  IConfigManagerInterface,
} from "../../../src/interfaces/IConfigManager";

const _abi = [
  {
    inputs: [],
    name: "maxTicketSalesDuration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxTicketSupplyAllowed",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minTicketSalesDuration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "procolFeesPercentage",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ticketSalesDurationLimits",
    outputs: [
      {
        internalType: "uint256",
        name: "minDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxDuration",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConfigManager__factory {
  static readonly abi = _abi;
  static createInterface(): IConfigManagerInterface {
    return new utils.Interface(_abi) as IConfigManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConfigManager {
    return new Contract(address, _abi, signerOrProvider) as IConfigManager;
  }
}
