/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INFTCollectionWhitelist,
  INFTCollectionWhitelistInterface,
} from "../../../src/interfaces/INFTCollectionWhitelist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "newNftCollection",
        type: "address",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
    ],
    name: "addToWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nftCollection",
        type: "address",
      },
    ],
    name: "getCollectionCreator",
    outputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nftCollectionToCheck",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nftCollectionToRemove",
        type: "address",
      },
    ],
    name: "removeFromWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INFTCollectionWhitelist__factory {
  static readonly abi = _abi;
  static createInterface(): INFTCollectionWhitelistInterface {
    return new utils.Interface(_abi) as INFTCollectionWhitelistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTCollectionWhitelist {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as INFTCollectionWhitelist;
  }
}
