/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRaffle,
  IRaffleInterface,
} from "../../../src/interfaces/IRaffle";

const _abi = [
  {
    inputs: [],
    name: "claimPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimTicketSalesAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "drawnTicket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nbOfTickets",
        type: "uint256",
      },
    ],
    name: "purchaseTickets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRaffle__factory {
  static readonly abi = _abi;
  static createInterface(): IRaffleInterface {
    return new utils.Interface(_abi) as IRaffleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRaffle {
    return new Contract(address, _abi, signerOrProvider) as IRaffle;
  }
}
