/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRandomProvider,
  IRandomProviderInterface,
} from "../../../src/interfaces/IRandomProvider";

const _abi = [
  {
    inputs: [],
    name: "requestRandomNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRandomProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomProviderInterface {
    return new utils.Interface(_abi) as IRandomProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomProvider {
    return new Contract(address, _abi, signerOrProvider) as IRandomProvider;
  }
}
