/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  ImplementationInterfaceNames,
  ImplementationInterfaceNamesInterface,
} from "../../../../src/libraries/helpers/ImplementationInterfaceNames";

const _abi = [
  {
    inputs: [],
    name: "AccessController",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6099610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063d4fc8823146038575b600080fd5b60516f20b1b1b2b9b9a1b7b73a3937b63632b960811b81565b60405190815260200160405180910390f3fea2646970667358221220ac6f6510a92d14995f9f750c29677bcc272b7c21a5d6fc0c27970a792e05967764736f6c63430008110033";

type ImplementationInterfaceNamesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ImplementationInterfaceNamesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ImplementationInterfaceNames__factory extends ContractFactory {
  constructor(...args: ImplementationInterfaceNamesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ImplementationInterfaceNames> {
    return super.deploy(
      overrides || {}
    ) as Promise<ImplementationInterfaceNames>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ImplementationInterfaceNames {
    return super.attach(address) as ImplementationInterfaceNames;
  }
  override connect(signer: Signer): ImplementationInterfaceNames__factory {
    return super.connect(signer) as ImplementationInterfaceNames__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImplementationInterfaceNamesInterface {
    return new utils.Interface(_abi) as ImplementationInterfaceNamesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ImplementationInterfaceNames {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ImplementationInterfaceNames;
  }
}
