/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace RandomProvider {
  export type ChainlinkVRFDataStruct = {
    vrfCoordinator: PromiseOrValue<string>;
    keyHash: PromiseOrValue<BytesLike>;
    callbackGasLimit: PromiseOrValue<BigNumberish>;
    requestConfirmations: PromiseOrValue<BigNumberish>;
    subscriptionId: PromiseOrValue<BigNumberish>;
  };

  export type ChainlinkVRFDataStructOutput = [
    string,
    string,
    number,
    number,
    BigNumber
  ] & {
    vrfCoordinator: string;
    keyHash: string;
    callbackGasLimit: number;
    requestConfirmations: number;
    subscriptionId: BigNumber;
  };
}

export interface RandomProviderInterface extends utils.Interface {
  functions: {
    "COORDINATOR()": FunctionFragment;
    "chainlinkVRFData()": FunctionFragment;
    "getRaffleFactory()": FunctionFragment;
    "implementationManager()": FunctionFragment;
    "rawFulfillRandomWords(uint256,uint256[])": FunctionFragment;
    "requestIdToCaller(uint256)": FunctionFragment;
    "requestRandomNumbers(uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "COORDINATOR"
      | "chainlinkVRFData"
      | "getRaffleFactory"
      | "implementationManager"
      | "rawFulfillRandomWords"
      | "requestIdToCaller"
      | "requestRandomNumbers"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "COORDINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chainlinkVRFData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffleFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementationManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requestIdToCaller",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomNumbers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "COORDINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chainlinkVRFData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRaffleFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementationManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestIdToCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomNumbers",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RandomProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RandomProviderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    COORDINATOR(overrides?: CallOverrides): Promise<[string]>;

    chainlinkVRFData(
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, number, BigNumber] & {
        vrfCoordinator: string;
        keyHash: string;
        callbackGasLimit: number;
        requestConfirmations: number;
        subscriptionId: BigNumber;
      }
    >;

    getRaffleFactory(overrides?: CallOverrides): Promise<[string]>;

    implementationManager(overrides?: CallOverrides): Promise<[string]>;

    rawFulfillRandomWords(
      requestId: PromiseOrValue<BigNumberish>,
      randomWords: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestIdToCaller(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    requestRandomNumbers(
      numWords: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  COORDINATOR(overrides?: CallOverrides): Promise<string>;

  chainlinkVRFData(
    overrides?: CallOverrides
  ): Promise<
    [string, string, number, number, BigNumber] & {
      vrfCoordinator: string;
      keyHash: string;
      callbackGasLimit: number;
      requestConfirmations: number;
      subscriptionId: BigNumber;
    }
  >;

  getRaffleFactory(overrides?: CallOverrides): Promise<string>;

  implementationManager(overrides?: CallOverrides): Promise<string>;

  rawFulfillRandomWords(
    requestId: PromiseOrValue<BigNumberish>,
    randomWords: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestIdToCaller(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  requestRandomNumbers(
    numWords: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    COORDINATOR(overrides?: CallOverrides): Promise<string>;

    chainlinkVRFData(
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, number, BigNumber] & {
        vrfCoordinator: string;
        keyHash: string;
        callbackGasLimit: number;
        requestConfirmations: number;
        subscriptionId: BigNumber;
      }
    >;

    getRaffleFactory(overrides?: CallOverrides): Promise<string>;

    implementationManager(overrides?: CallOverrides): Promise<string>;

    rawFulfillRandomWords(
      requestId: PromiseOrValue<BigNumberish>,
      randomWords: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    requestIdToCaller(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    requestRandomNumbers(
      numWords: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    COORDINATOR(overrides?: CallOverrides): Promise<BigNumber>;

    chainlinkVRFData(overrides?: CallOverrides): Promise<BigNumber>;

    getRaffleFactory(overrides?: CallOverrides): Promise<BigNumber>;

    implementationManager(overrides?: CallOverrides): Promise<BigNumber>;

    rawFulfillRandomWords(
      requestId: PromiseOrValue<BigNumberish>,
      randomWords: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestIdToCaller(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestRandomNumbers(
      numWords: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    COORDINATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    chainlinkVRFData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRaffleFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    implementationManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rawFulfillRandomWords(
      requestId: PromiseOrValue<BigNumberish>,
      randomWords: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestIdToCaller(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requestRandomNumbers(
      numWords: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
