/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IRaffleFactory {
  export type ParamsStruct = {
    purchaseCurrency: PromiseOrValue<string>;
    nftContract: PromiseOrValue<string>;
    nftId: PromiseOrValue<BigNumberish>;
    maxTicketSupply: PromiseOrValue<BigNumberish>;
    ticketPrice: PromiseOrValue<BigNumberish>;
    ticketSaleDuration: PromiseOrValue<BigNumberish>;
  };

  export type ParamsStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    purchaseCurrency: string;
    nftContract: string;
    nftId: BigNumber;
    maxTicketSupply: BigNumber;
    ticketPrice: BigNumber;
    ticketSaleDuration: BigNumber;
  };
}

export interface RaffleFactoryInterface extends utils.Interface {
  functions: {
    "batchRaffleDrawnTickets(address[])": FunctionFragment;
    "createNewRaffle((address,address,uint256,uint256,uint256,uint64))": FunctionFragment;
    "isRegisteredRaffle(address)": FunctionFragment;
    "randomProvider()": FunctionFragment;
    "requestIdToContracts(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchRaffleDrawnTickets"
      | "createNewRaffle"
      | "isRegisteredRaffle"
      | "randomProvider"
      | "requestIdToContracts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchRaffleDrawnTickets",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createNewRaffle",
    values: [IRaffleFactory.ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredRaffle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "randomProvider",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestIdToContracts",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchRaffleDrawnTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNewRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestIdToContracts",
    data: BytesLike
  ): Result;

  events: {
    "NewRaffle(address,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewRaffle"): EventFragment;
}

export interface NewRaffleEventObject {
  raffleContract: string;
  globalData: IRaffleFactory.ParamsStructOutput;
}
export type NewRaffleEvent = TypedEvent<
  [string, IRaffleFactory.ParamsStructOutput],
  NewRaffleEventObject
>;

export type NewRaffleEventFilter = TypedEventFilter<NewRaffleEvent>;

export interface RaffleFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RaffleFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchRaffleDrawnTickets(
      _raffleContracts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createNewRaffle(
      _params: IRaffleFactory.ParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isRegisteredRaffle(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    randomProvider(overrides?: CallOverrides): Promise<[string]>;

    requestIdToContracts(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  batchRaffleDrawnTickets(
    _raffleContracts: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createNewRaffle(
    _params: IRaffleFactory.ParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isRegisteredRaffle(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  randomProvider(overrides?: CallOverrides): Promise<string>;

  requestIdToContracts(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    batchRaffleDrawnTickets(
      _raffleContracts: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    createNewRaffle(
      _params: IRaffleFactory.ParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    isRegisteredRaffle(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    randomProvider(overrides?: CallOverrides): Promise<string>;

    requestIdToContracts(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "NewRaffle(address,tuple)"(
      raffleContract?: PromiseOrValue<string> | null,
      globalData?: null
    ): NewRaffleEventFilter;
    NewRaffle(
      raffleContract?: PromiseOrValue<string> | null,
      globalData?: null
    ): NewRaffleEventFilter;
  };

  estimateGas: {
    batchRaffleDrawnTickets(
      _raffleContracts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createNewRaffle(
      _params: IRaffleFactory.ParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isRegisteredRaffle(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    randomProvider(overrides?: CallOverrides): Promise<BigNumber>;

    requestIdToContracts(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchRaffleDrawnTickets(
      _raffleContracts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createNewRaffle(
      _params: IRaffleFactory.ParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isRegisteredRaffle(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    randomProvider(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requestIdToContracts(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
